//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int Admin_Id { get; set; }
        [Required(ErrorMessage ="Admin Email Required")]
        [EmailAddress(ErrorMessage ="Invalid Email")]
        public string Admin_Email { get; set; }
        [Required(ErrorMessage = "Admin Password Required")]
        [EmailAddress(ErrorMessage = "Invalid Password")]
        public string Admin_Password { get; set; }
    }
}
