//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrer
    {
        public int career_id { get; set; }
        public string carrer_designation { get; set; }
        public string carrer_qualfication { get; set; }
        public string career_description { get; set; }
        public string send_resume { get; set; }
    }
}
