//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int person_id { get; set; }
        public string person_name { get; set; }
        public int person_phone { get; set; }
        public string person_email { get; set; }
        public string messages { get; set; }
    }
}
