//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dinetable
    {
        public int Dine_Id { get; set; }
        public string Person_Name { get; set; }
        [Display(Name = "Name")]
        public int Person_Number { get; set; }
        [Display(Name = "Date")]
        public System.DateTime Dine_Date { get; set; }
        [Display(Name = "Time")]
        public System.TimeSpan Dine_Time { get; set; }
        [Display(Name =" Outlet")]
        public Nullable<int> Outlet_Bid { get; set; }
    
        public virtual Outlet Outlet { get; set; }
    }
}
