//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Jobrespons
    {
        public int user_id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Job_Position { get; set; }
        public string Resume { get; set; }
        public HttpPostedFileBase Resum { get; set; }
        public int Phone { get; set; }
    
        public virtual Carrer Carrer { get; set; }
    }
}
