//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Outlet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Outlet()
        {
            this.reserves = new HashSet<reserve>();
        }
    
        public int outlet_id { get; set; }
        public string outlet_name { get; set; }
        public string outlet_disc { get; set; }
        public string outlet_location { get; set; }
        public string outlet_pic { get; set; }
        public HttpPostedFileBase outle_pic { get; set; }
        public Nullable<int> branch_fid { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserve> reserves { get; set; }
    }
}
