//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int receiptid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int contactNumber { get; set; }
        public string address { get; set; }
        public int amount { get; set; }
    }
}
