//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int Prod_Id { get; set; }
        [Required(ErrorMessage ="Enter  Product Name")]

        public string Prod_Name { get; set; }
        [Required(ErrorMessage = "Enter  Product Description")]
        public string Prod_Disc { get; set; }
        [Required(ErrorMessage = "Enter  Purchase Price")]
        public string Purchase_Price { get; set; }
        [Required(ErrorMessage = "Enter  Sale Price")]
        public string Sale_Price { get; set; }
        [Required(ErrorMessage = "Enter  Product Pic")]
        public string Prod_Pic { get; set; }
        [Required(ErrorMessage = "Enter  Product Pic")]
        public HttpPostedFileBase Pro_Pic { get; set; }
        [Required(ErrorMessage = "Enter  Product Category")]
        public int Cat_Fid { get; set; }

        public int PRO_QUANTITY { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
