//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserve
    {
        public int reserve_id { get; set; }
        public string cus_name { get; set; }
        public int cus_phone { get; set; }
        public System.DateTime reserve_date { get; set; }
        public System.TimeSpan reserve_time { get; set; }
        public int persons_count { get; set; }
        public int cus_fid { get; set; }
        public int out_fid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Outlet Outlet { get; set; }
    }
}
